### ISSUE TITLE
MEGA65+C65: missing CIA TOD 0.1 second counter

### ISSUE THREAD

**Issue by steph72** [lgblgblgb/xemu#129]
It seems that the jiffy clock only updates every second, as can be verified with

`DO:PRINT TI:LOOP`

Unfortunately, this makes fine grained timing loops in BASIC 10 impossible.

**Comment by lgblgblgb** [comment]
Thanks for the report. This is a design constraint, Xemu being cross-platform (Linux/UNIX,Windows,MacOS,web/emscripten) there is no finer real-time clock source, also emulation speed would diverge from CIA TOD (as I believe the TI and TI$ source of C65 is CIA TOD ... unlike C64, which causes the problem since it cannot be synced ever correctly to the emulation speed) anyway or makes "jumps" which would be very noticeable on higher resolution. To really cure this, basically everything should be rewritten. Which may happen at some time, as that's the correct behaviour.

Anyway **I will** try to make at least some workarounds to handle this till now, but I wouldn't do too much precise timing with that (can be as precise probably that +/- 0.2sec can be achieved which 0.1sec uncertainty).

_The other possibility would be to count TOD in emulation time (ie not real-time of the OS which runs the emulator), but then TOD will quickly diverge from the true system time, though more precise timing it would be able to provide._

Btw, this affects both C65 and MEGA65 emulation as they're using the same CIA emulation framework.

Thanks again for the report, and stay tuned.

**Comment by lgblgblgb** [comment]
00d69186a21e28e5bb0f5ab039b14d7f8eaf347a
