### ISSUE TITLE
MEGA65: Implement a small border

### ISSUE THREAD

**Issue by Edilbert** [lgblgblgb/xemu#221]
It would be nice to have a border around the screen emulation.
Currently border colours and changing of it cannot be seen.
The border doesn't need to be of precise extent, just a small border, showing the border colour.

**Comment by lgblgblgb** [comment]
Thanks for the report, however in this form it's invalid. This is because it's not that it can be done this way, it's simply lack of a better VIC-IV emulation, thus the solution here is not to emulate border, but using better VIC-IV emulation in general. Which is already done in Hernan's experimental VIC-IV enhancement branch, which will be merged into mainline Xemu some time, hopefully not in the far future. Of course that also implements border, among **many** other things in terms of better VIC-IV emulation.
