### ISSUE TITLE
General C64 emulation issues

### ISSUE THREAD

**Issue by BacchusFLT** [lgblgblgb/xemu#247]
The ambition of this emulator might not be that the c64 emulation is on par with the dedicated c64 emulators, but never the less running this program, a number of c64 emulation issues surface:

https://csdb.dk/release/?id=200257  (Use the 1581 option)

Preparatory:
* For some reason after a hard reset, the c64 starts in 2MHz mode. You can poke it back to 1 MHz using POKE 53296,0 but really the c64 should start in 1MHz.
* A hard reset forgets the image in the drive and reverts back to some default one. That also doesn't make sense. The disk in the drive is the disk in the drive.

![image](https://user-images.githubusercontent.com/28536010/118401280-5d684a00-b665-11eb-8d36-36dac83671fc.png)

Crack intro
* The logo at top of the screen looks really poor. My assumption is that this is how the logo would look in hires mode. Doesn't multicolour work?
* The sprite animation is gone.
* The scroller is not at all smooth

![image](https://user-images.githubusercontent.com/28536010/118401342-986a7d80-b665-11eb-9238-a816ccd700bf.png)

Game intro (part 1 - after keypress and selecting options for the trainers):
* The game intro is bitmap and also here the graphics is totally trashed and look like hires
* Please mind: Here the same sprite as in the intro *does* work.

![image](https://user-images.githubusercontent.com/28536010/118401510-44ac6400-b666-11eb-8e99-a99b4eb1bf63.png)

Game intro (part 2 - after a long wait in the Game intro Part 1)
* Logo and other graphics here is also multicolour but looks presented as hires.
* The background should also be black but it's not

After game intro 2, the game continues to load using the custom loader, and that fails.

**Comment by lgblgblgb** [comment]
The problem here, that the old VIC emulation is a dead-end, and you seem to use that version (you can recognize it, since it does not emulate border at all). So any VIC (let it be VIC-IV, VIC-III or VIC-II) emulation related problems should be checked against the newer VIC emulation core, which can be found in Hernan's branch (`hmw` branch). Unfortunately the current situation that `hmw` carries more decent VIC emulation but everything is much older. In contrast, `next` is the newest in everything other than VIC/gfx emulation in general. We're in the process of merging those together into a single "official" entity. You can learn about this more here: #29

**Comment by lgblgblgb** [comment]
I close this, since it's probably against the `master` branch which is very old. In fact even `next` wouldn't be enough for this, because of the problem mostly about VIC emulation precision (and other facts like 1/2MHz problem is addressed in `next` at the other hand). Thanks for your time to make a nice issue!
