### ISSUE TITLE
Machine code monitor

### ISSUE THREAD

**Issue by BacchusFLT** [lgblgblgb/xemu#248]
In order to search for where problems arise within the emulation, a machine code monitor would be MOST helpful.

**Comment by lgblgblgb** [comment]
This will be **never** implemented. This is a design choice. **But let me explain why!** And debugger must be external, as with the real MEGA65, in fact, the same external debugger can connect to both of a real MEGA65 and Xemu. There is no need for "internal" debugger in Xemu, what I wanted to say, and also would go against the goal to emulate a real MEGA65 which has external debugger for this purpose, so its emulation must be too. In this respect, Xemu emulation of MEGA65 is very different from (eg) a C64 emulator, since a C64 is a well established "old" machine, however MEGA65 is a new design to allow remote debugging even in its "physical" form without any emulation but the real machine. Thus, the emulation of MEGA65 must follow that route to, in the name of good emulation. It also allows to develop external debuggers even multiple ones, by anybody who wants.

**Comment by lgblgblgb** [comment]
Thanks for your report, however I close this, since it's considered "invalid" request, as debugger is not something should be in Xemu, as I explained above.

**Comment by BacchusFLT** [comment]
There is a need for a machine code monitor/debugger, but how it's implemented is another matter. I would hope there is an interface that will allow an external monitor to access the machine.

**Comment by lgblgblgb** [comment]
There is even currently, using the same protocol as MEGA65, can be used with `m65dbg`. It's another question that in this state, we have multiple problems, like:

* `m65dbg` is not mature enough, and CLI-only, also maybe not so comfortable for most users
* Xemu does not implement **every** aspects of the protocol yet (Gurce "likes" to play with that and fixing things though)
* the current on-going merge of VIC emulation will break the monitor/debug interface badly :( That will be fixed for sure, but here it is a conflict, that either we don't have nicer VIC emulation or break debugging for a while ... :-/
* core problem shared with MEGA65 as well, that it's about the CPU, we can't "stop" generating video signals, so it's problematic to debug programs depending on exact VIC timing, or interaction with it (including raster IRQ for example)
