### ISSUE TITLE
MEGA65: correct VIC-IV RRB behaviour

### ISSUE THREAD

**Issue by deftmega** [lgblgblgb/xemu#255]
Please add full raster rewrite behaviour including Y positioning.

For example on Turrican Demo:

[turricandemo.zip](https://github.com/lgblgblgb/xemu/files/6511598/turricandemo.zip)

(probably also fails to load due to floppy code issue)

**Comment by lgblgblgb** [comment]
@deftmega Note, that RRB implementation in Xemu was mostly a kind of "hack" MEGAMAZE to be able to work. Surely there are much more to it back to then, and now even more features/changes which must be implemented, indeed!

**Comment by lgblgblgb** [comment]
#265 seems to fix the GOTOX issue in H320 mode. Sure, this issue is in general about RRB but it includes that too, that's why I have this comment here now.

**Comment by lgblgblgb** [comment]
Though, I would suggest, we should list/discover all the pending RRB problems, "full implementation" is kinda of vague what it means. Is there anything than #265 had, and the Y positioning?

**Comment by lgblgblgb** [comment]
Now the question what we missed from RRB still, that is scope of this issue.

**Comment by lgblgblgb** [comment]
#232 is closed in favour of this issue.

**Comment by lgblgblgb** [comment]
So, have we anything left from this issue still to work on, or can be closed?

**Comment by deftmega** [comment]
Can't really test at the moment because Shallan's game all use the same disk loader which still got an open issue - sorry!

**Comment by lgblgblgb** [comment]
Yes, that's my problem too, that not so much choice to test with because of other problems. But thanks for the effort :)

**Comment by lgblgblgb** [comment]
I'm tending to close this, since it's too generic issue, maybe individual problems should be addressed as their own. Like now that "negative GOTOX" alone is a separate issue. It regards of Turrian at least, Shallan now uses a modified loader which works. Turrican demo runs, there are some interesting "garbage" at the left and at the right of the vertical borders, which may be another issue or who knows at this point at least. But in general, this is very much "almost perfect" at least compared how it was before ;) Shallan noted, that even he needs to refresh his memories how the scroll was done in his demo, which may cause the problems. But anyway, I would say, if something pops up with the need of fixing, it's may be better to address in separated/dedicated issue.
