### ISSUE TITLE
MEGA65: VIC-IV alternate palettes on RRB 

### ISSUE THREAD

**Issue by smnjameson** [lgblgblgb/xemu#273]
in NCM 16 color char mode alternate palettes can be selected by setting the BOLD + REVERSE attributes in the GOTOX marker. Note this relies on the extended attributes being disabled in bit5 of $d031 otherwise it will have no effect:

**Expected:**
![image](https://user-images.githubusercontent.com/4640763/121036878-eaa34800-c7a6-11eb-982c-e92b9e4236f1.png)

_Note how one of the moving balls is a different color_

**Xemu actual:**
![image](https://user-images.githubusercontent.com/4640763/121036663-c5163e80-c7a6-11eb-9e87-d4765ff2c68a.png)

**Test Files (Menu option B-D)**
[vic4tests.zip](https://github.com/lgblgblgb/xemu/files/6609889/vic4tests.zip)

**Comment by lgblgblgb** [comment]
So, it seems background also needs to use the "new" palette (the alternate palette) may be selected with GOTOXY. In fact as @smnjameson mentioned maybe everything from that point uses that palette (surely not sprites as those have separate palette optionally), not even restricted to NCM. Actually this is not too bad, I introduce the `used_palette` pointer which is initialized to the actual palette on each scanline start, but can be modified by the GOTOX token. Surely, renderers should use this `used_palette` then instead of the `palette`.

**Comment by lgblgblgb** [comment]
Edited issue name to better reflect it's not only for NCM

**Comment by lgblgblgb** [comment]
I consider this now as being done, since no more complains/bugs since them, I am aware of, at least.
