### ISSUE TITLE
MEGA65: VIC-IV RRB GOTOX wrap boundary < $000 issue

### ISSUE THREAD

**Issue by smnjameson** [lgblgblgb/xemu#275]
The GOTOX position of the rewrite buffer runs from $000 to $3ff and wraps around, this means to display something off the left side, partially behind the border as so:

![image](https://user-images.githubusercontent.com/4640763/121056425-17ab2700-c7b6-11eb-900f-1e54556487f1.png)
_Note the green rectangle is partially behind the left border_

The GOTOX must be set to a negative value and as this number uses 10 bits ($000-$3ff) that means $3ff is -1 , $3fe is -2 etc

Xemu just stops displaying anything that doesn't fit between $000-$13f

Test Files (Menu Option B-E)
[vic4tests.zip](https://github.com/lgblgblgb/xemu/files/6610657/vic4tests.zip)

**Comment by lgblgblgb** [comment]
The position if it was "negative" was off by one pixel, I think, since `$3FF` should be -1, but `$3FF - pos` was used, resulting in zero. Hopefully it's better now, though may not even be noticeable too much.

**however** still there is a serious issue, if ever used: position won't wrap around. I don't know if it's really a problem. What I mean here, that people can set things like $300, and expecting to "warp around" to zero eventually. My current solution is a hack, and it just initially (on GOTOX time) tests, if it should be interpreted as negative (then it's OK), but won't wrap around ever, if initially it wouldn't "behind" the border when GOTOX instructs it.

**Comment by lgblgblgb** [comment]
Since it _seems_ to be OK now, I close this.
