### ISSUE TITLE
MEGA65: VIC-III extended text attributes emulation precision

### ISSUE THREAD

**Issue by hernandp** [lgblgblgb/xemu#281]
Our current emulation when blinking bit is set is not accurate (it just checks for RVS bit and turns pixel OFF otherwise).

The hardware output is shown in https://www.youtube.com/watch?v=k86o4PBod4I

**Comment by lgblgblgb** [comment]
By the way, video is nice - do not misunderstand - but I always find the best to have actual screenshot, from MEGA65 and Xemu so clearly the difference can be seen. It can help a lot to quickly review the issue and even later, only a second of look on the images and the problem is clear. Surely with "blinking" for example, it's kinda tricky with a still image, that's true ;)

**Comment by hernandp** [comment]
Agreed @LGB!

I already have the fix at 90%, I will post differences before and after
(and code to reproduce of course).
