### ISSUE TITLE
MEGA65: $d610 key detection not working

### ISSUE THREAD

**Issue by smnjameson** [lgblgblgb/xemu#311]
Using the SID player from https://files.mega65.org?id=5ce1c3cf-8a83-491a-8201-89b06137b0a6
You are unable to select any other song using the keyboard as you can on real HW, until you enable and then disable the mousegrab options in the input menu.

The player uses $d610 to read the ASCII key value

**Comment by lgblgblgb** [comment]
Xemu does emulate that feature.

## Hardware accelerated keyboard scanner

$D610 maintains a "queue" of pressed chars in the past, to be more precise (AFAIK ...) a 4 bytes long buffer. Reading $D610 will provide the last char (ASCII value) in the buffer (or zero, if there is no character) without removing the character though. To remove the top-most item, a write should be performed on $D610 (the actual written value does not count, just the fact of writing something).

## My theory about the incompatibility

As far as I can imagine, the player does not remove the read character from the queue in some cases, like when it's not the desired 1,2,3,4,5 values to select a song. Since the (emulated) machine was used before, the $D610 buffer already contains some character, which probably not the expected 1,2,3,4,5 values. The player seeing not the right keys pressed, may forget to remove the character, so it never gets the new ones.

However, I admit, I **cannot explain** why it works still on the hardware! To my best knowledge at least, $D610 should work like this.

The "mouse grab trick" works as a workaround for different reasons, not related to this issue too much: since Xemu maintains at least two ways to detect keypresses (during the emulation, and using any GUI primitives, like warning box about mouse grab displayed), it has to reset the input pending events to avoid "leaking" key events to one subsystem to another. So the sole reason it seems to help, is because the reset even queue.

**Comment by smnjameson** [comment]
The problem is the discrepancy between HW and Xemu without writing to it

Real HW refreshes on key press, but Xemu not.
### On Xemu
- When writing Xemu remembers 2 keys
- press 1 then 2, and now D610 = $31
- write $00 to $d610 and it changes to $32
- 3rd or more keys with same method are ignored


### On Real HW
- Press 1 then 2 then 3
- D610 changes from $31 to $32 to $33 without any writing to $d610
- write $00 to $d610 and $d610 is now $00 stays at $00


So it would seem writing to $d610 only has the effect of assisting you with acknowledging you have read the ASCII value, to prevent some code running twice or more per key press.

Could just be a misinterpretation of the manual: "Write to clear event ready for next", which I guess should be clarified in the documentation.

**Comment by lgblgblgb** [comment]
Seems to be some issue in mega65-core as well, see: https://github.com/MEGA65/mega65-core/issues/465

**Comment by lgblgblgb** [comment]
I close this issue now in favour of #148 . That's a long pending issue to correctly emulate the buffer-length. Now it's the question what it should be and how exactly it should behave, so I think, it's really up to that issue to be solved and closed after the solution!
