### ISSUE TITLE
MEGA65: Head and side are not maintained across drives

### ISSUE THREAD

**Issue by jimnicholls** [lgblgblgb/xemu#315]
**Describe the bug**
In f011_core.c, there is only a single `head_track` and `head_side` variable. Switching between drive 0 and drive 1, the emulation doesn't switch to where the heads are for the new drive. `head_track` and `head_side` stay with the values for the old drive.

**Used version of the project**
lgblgblgb/next commit 9606dfdf64c28b2f2d2178de7ea260594c9d4ce5

**To Reproduce**
Assuming two formatted disk images: a.d81 and b.d81.
1. `xmega -8 a.d81 -9 b.d81`
2. Using the F011, spin up drive 0, seek to track 0, seek to track 40, and then spin down drive 0. `head_track` will now be 40.
3. Spin up drive 1. `TK0` will be set. But `head_track` will still be 40.
4. Move the heads of drive 1 out by one track. The heads of drive 1 will be on track 1, but `head_track` will be 41.

**Expected behavior**
When setting F011's `DS`, xemu's understanding of where the heads are updates to the newly selected drive.

**Additional context**
This is all irrelevant to xemu, because it (today) it doesn't emulate any actually floppy drive. It only emulates an SD card, and doesn't care where the heads actually are. It will always just find the sector. It only uses head_track to set TR0 and prevent the heads passing in beyond track 0 and out beyond track 128.

I'm trying to right code that might work on a floppy disk. So I'm trying to carefully move the heads to the correct track before trying to read the sector. To the end, I've enabled DEBUG and am watching the output when moving the heads and confirming that head_track = track when reading. So I need `head_track` and `head_side` to be accurate.

**Comment by jimnicholls** [comment]
Pull request incoming.

**Comment by jimnicholls** [comment]
I just read your PR template. So I won't create a PR yet.

You see what I was going to propose at https://github.com/jimnicholls/xemu/commit/2ba32ac993298c4e98eb2605503a7329c5d6a278.

What I did was move `head_track` and `head_side` inside `drives`. Then replaced all the references to `head_track` with `drives[drive].head_track`, and similarly for `head_side`.

I also moved the initialisation of `drives[which].head_track` and `drives[which].head_side` inside `fdc_set_disk`. Maybe controversially I only initialised them when `in_have_disk` is true. Kind of simulating that if there's no disk in the drive, `head_track` and `head_side` are undefined.

**Comment by lgblgblgb** [comment]
Thanks for your report!

Please note, that these kind of things are currently "WIP" by me (also) because of other issues, mainly this one: #314 Even this case you mention, but it seems there can be more problematic cases, but probably in the other direction (ie, something is split off per drives, which shouldn't be - the opposite in nature than this problem).

Yes, this part of emulation is originally was written with one drive only keeping in mind (also in a way that nobody could tell how it works, so most of F011 emulation is just try&error, it was even before MEGA65 worked with any FDC access, let it be the physical drive or "D81 mount" from the SD-card), and was just "raped" to handle more drives, with the possible problem of forgetting to adjust things. This is what I'm working on, under the issue #314 , what I've mentioned above.

Yes, it's always nice to discuss first, since most of the cases (but surely, not always!!!!!!!) I know about the problem to some extent and I may be already working on that.

**Comment by lgblgblgb** [comment]
Huh, sorry, I totally forgot about this, though it was already made in my local working copy, uncommitted ... :(
