### ISSUE TITLE
MEGA65 ROM "how to get it" tutorial for Xemu <- rom patch dosent work tried with bsdiff and m65connect on linux

### ISSUE THREAD

**Issue by amig420** [lgblgblgb/xemu#347]
**Describe the bug**
did rom patch to original rom from zimmers page.  original rom unpatched works fine on c65 xemu emulator.  

 131072 Jun 10 02:53 910828.bin
sha256sum 910828.bin 
0c4a00b45b65ca553b8a9f38cae83fe5f7dca7e809c24c0051ae40956640509d  910828.bin

tried lastest and other bdf fiiles.  Results always the same.  Blue screen when mega65 boots. no text on emulator screen whatsoever.

**Used version of the project**
Source of the binary you use, version. Full dump on the console (start from
console, and/or enable console to see). It shows the version, compilation
method, many useful information, maybe additional messages, warnings and
errors as well!

**To Reproduce**
Steps to reproduce the behavior. As steps as required, do not try to squeeze
everything into one step.
1. ...
2. ...
...
bspatch 910828.bin new.bin 920366.BDF 

**Expected behavior**
expected mega65 rom start screen with READY prompt
**Screenshots**

**Computer/Device (please complete the following information):**
 - Device/Platform: [e.g. Mac, PC, Raspberry Pi, ...]
 - OS and its version: [e.g. iOS 8.1, Ubuntu Linux 18.04.2 64 bit, Windows 10 64 bit, ...]
 - Browser and its version - _if applies_: [e.g. Safari, Firefox]
Linux pop-os 5.17.5-76051705-generic #202204271406~1653440576~21.10~6277a18 SMP PREEMPT Wed May 25 01 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
![screenshot-20220611-001331](https://user-images.githubusercontent.com/107284145/173162951-2919c701-0a9d-427a-82f5-7db7b06e3bca.png)
![Screenshot from 2022-06-11 00-39-44](https://user-images.githubusercontent.com/107284145/173163025-d4c2c04e-36a6-48fb-b429-b7a8ff458dc4.png)

**Comment by lgblgblgb** [comment]
Thanks for the report However I cannot help easily here (ie not an emulator issue) all ROMs are tested and works, so must be some kind of patching issue. Unfortunately neither bspatch/bsdfif nor m65connect was not written by me, so I am not sure what went wrong here for you to be honest.

You mentioned  920366.BDF so I suppose you tried with the hope you get the 920366 ROM. For me, with that version the SHA256 sum for that ROM is:

2fe8fe4b5a337e6ef0e0435d8088b43ac6e99cd6fe86c36a0e2122e265bfd88c

Please compare, if you got other checksum after patching, then something is wrong with patching, and nothing to do with Xemu. The result here:

![xemu](https://user-images.githubusercontent.com/884916/173181087-45ae3807-0f86-4d08-835e-23bc6e1e9cd4.png)

**Comment by lgblgblgb** [comment]
My workflow (just tested to make sure it really works):

    lgb@rygel:/tmp/bug$ sha256sum 910828.bin 920366.BDF
    0c4a00b45b65ca553b8a9f38cae83fe5f7dca7e809c24c0051ae40956640509d  910828.bin
    47970d6fef13fe196c416a63251f710306e74ea896539c81923d02b05b3204a3  920366.BDF
    lgb@rygel:/tmp/bug$ bspatch 910828.bin new.bin 920366.BDF
    lgb@rygel:/tmp/bug$ sha256sum new.bin
    2fe8fe4b5a337e6ef0e0435d8088b43ac6e99cd6fe86c36a0e2122e265bfd88c  new.bin

I've added some checksumming so you can check the steps getting the same result at all. The result here, `new.bin` is the ROM we want to use. Then, in Xemu: right click into the emulator window, select Disks -> SD-card -> Update files on sd-image. Make sure you say "no" if/when Xemu asks for "Use the previously installed ROM?" as you want to install a new ROM, then select the ROM you got from the process above, ie `new.bin` in my case.

After that Xemu warns that it reset itself, and you should see the what I've posted above (the screenshot).

I used bspatch on Ubuntu Linux intalled by:

`sudo apt install bsdiff`

version info:

`Version: 4.3-21`

**Comment by amig420** [comment]
az@pop-os:~/Downloads/mega65$ sha256sum 910828.bin 
0c4a00b45b65ca553b8a9f38cae83fe5f7dca7e809c24c0051ae40956640509d  910828.bin
baz@pop-os:~/Downloads/mega65$ sha256sum 920366.BDF 
47970d6fef13fe196c416a63251f710306e74ea896539c81923d02b05b3204a3  920366.BDF
baz@pop-os:~/Downloads/mega65$ bspatch 910828.bin new.bin 920366.BDF 

sha256sum new.bin
2fe8fe4b5a337e6ef0e0435d8088b43ac6e99cd6fe86c36a0e2122e265bfd88c  new.bin

same results as you.  version bsdiff - 4.3-22

still same problem.

 i looked at my download directory and i may have downloaded xemu from the xemu website on september 22.  

in the near future, i will possibly either download a newer build or git clone xemu.

may i ask which version of xemu you are current using to acheive these results.

**Comment by amig420** [comment]
i downloaded the latest ubuntu package from the xemu site @ https://github.lgb.hu/xemu/index.html?showversions=20210917105807&timeid=1655077935.482.

i now have working mega 65. :) thanks

**Comment by lgblgblgb** [comment]
@amig420 I am not aware basically any problem causing similar thing, regardless of version and branch, that's also the reason I am very much interested to see what causing this for you. But in general, to answer your questions, the "master" (aka 'stable') branch and the 'next' branch are should be OK. September 22 is quite old btw, I am not sure if it supposed to work with a very decent ROM as MEGA65 itself is changed since then as well, of course Xemu too, probably even an old MEGA65 (real one) with a core dated back to September wouldn't work either.

So no idea what happened with your situation maybe indeed. Though if you really used an old version of Xemu like Sep 22, it may explain things: for example Q-opcodes of the MEGA65 CPU wasn't even implemented back to then, "only" at the end of November. And newer ROMs uses Q-opcodes, so it can explain the situation. This seems to be the most likely explanation, so I close this issue now. Note, that even sometimes 1-2 weeks old stuff is "too old" as well, MEGA65's (and of course its emulator) still undergo rapid changes/fixes from time to time.

**Comment by skj-1971** [comment]
i cant get passed the intoductio which i got after xemu created the  vertual rom
also  when ging into utillities to format an 4gb sd i have nomenu just a grey box   can  some one  help

**Comment by lgblgblgb** [comment]
@skj-1971 
> i cant get passed the intoductio which i got after xemu created the vertual rom also when ging into utillities to format an 4gb sd i have nomenu just a grey box can some one help

This is really a bad place for help, different issue and a closed one already. But anyway:

1. Gray box on "menu": that's normal, limitation of Xemu, you shouldn't use or need to use that anyway
2. If you get the introduction screen (I mean that blue-shades scrolling background, right?) it means everything is OK, you just need the ROM. It also means that SD-card is properly formatted by first run of Xemu, so you don't need that. In fact that is a ROM, just the "stub ROM" of Xemu, which is there you have something to see at least while you supply a real ROM.

However this is already out of scope of the emulator, as I cannot ship the ROM with xemu, and also I can't just give you one: I would like to do so, but it's a copyright/legal issue of the ROM unfortunately. So unfortunately I cannot help too much on getting a ROM, but this issue was originally about that, how someone get one with some work of patching/etc. Again, this is out of scope of Xemu, every emulators (let it be Amiga or C64 or MEGA65 etc emulator) needs the machine's ROM.

If you have the ROM, what you should do then (no, no need to format the emulated SD-card), two choices:

1. Open the preferences directory of Xemu (if you don't know where, right click into the emulator window, select "Debug / Advanced" and then "Browse system folder"). You need to put the ROM there with the **exact name** of `MEGA65.ROM` and indeed it must be capitalized this way. You may need to exit and re-start Xemu.
2. You can use Xemu itself to install the ROM: use the UI again (right click into the emulator window) then select "Disks" then "SD-card" then "Update files on the SD-card". If a question appears that you want to use the previous ROM, select NO. Xemu will pop-up a file open dialog box, and you need to feed it with a MEGA65 ROM image.
