### ISSUE TITLE
UI: Xemu affects Windows 10's night shift mode

### ISSUE THREAD

**Issue by godot64** [lgblgblgb/xemu#351]
Everytime you ran Xemu, the **Windows 10 night shift** is turned off. You can only re-start the computer to get rid of this setting, (which I think is) invoked by Xemu. 

This occurs on any version of Xemu and any version of Mega65 ROM.

**Comment by lgblgblgb** [comment]
Thanks for the report. Xemu alone does nothing to turn any feature like this on/off, so I have the suspect that it's something done by SDL2 itself what Xemu uses, as Xemu is basically an SDL2 application. Honestly I am not even aware of that feature as my whole Windows experience is because of porting and supporting Xemu for Windows users, I never use Windows otherwise. But I'll try to google for some solution what SDL2 exactly does internally which can cause this ...

**Comment by godot64** [comment]
I see! You probably use this Flag: SDL_SetWindowGammaRamp and set it to max values?

Arndt

**Comment by lgblgblgb** [comment]
Isn't this a Windows bug? I mean an application of any OS should not have ever any impact on the OS after the program terminates and no longer running. However you wrote, that you need to re-start your computer to get back this functionality regardless (?) you have quitted Xemu already. In my eye, it is a serious windows problem, Microsoft should be fixed. Surely I am all with fixing Xemu bug, I don't write this just I don't need to do anything, just it sounds very strange for me ... So for sure I can start to experiment with workarounds but somehow I feel it's like I want to fix Windows from Xemu ;) But ok, let is be. back to the main topic: I am not really sure what I can do with that SDL2 function. It expects a 256 element Uint16 array for the R, G and B channels. So I suppose I should create some gradient table or so. But in any way, trying to set it myself seems to defeat the purpose since if I try to set some default gamma mapping table is the opposite of these kind of night modes which intended not to use the default mapping, but some other kind to shift colours to the yellow-kind spectrum and reduce blue ... Maybe I can try to use the "Get" variant of the mentioned function and store result and re-apply before exit? But not sure when SDL2 decides (and how it does that!) to mess Windows' idea on this night mode. Unfortunately I haven't found any too much relevant info, trying to google for similar problems with Windows by SDL2.

**Comment by godot64** [comment]
> Maybe I can try to use the "Get" variant of the mentioned function and store result and re-apply before exit? 

This was my idea. I assume that a windows application gets this array on startup and rebuilds it when exiting. Not sure if that assumption matches the win10 guidelines. 

Anyway, I just stumbled upon this behavior, so I thought I'll report it.

**Comment by lgblgblgb** [comment]
Yes, I've quoted some findings above already that it seems there are issues with nightshift according to google, that was the main reason I was a bit sceptical that I can help with that, if it's more an OS issue than Xemu's ...

No problem, every report can be important, and we cannot know at the beginning what kind of issue it is. So it's better to report and investigate at least to some degree than ignoring reports right at the beginning! So please feel free in the future to report issues/ideas, and do not feel bad about that. Thanks.
