### ISSUE TITLE
MEGA65: PRG run option (UI/CLI) should work on all (closed) ROM versions

### ISSUE THREAD

**Issue by MightyAxle** [lgblgblgb/xemu#364]
When using Windows with XMEGA65.EXE on ROM build 990003 it is not possible to run PRG files. Only attaching Disk Images is possible.

If a PRG is selected to run nothing happens. If you try and load the PRG as a Disk image a read error occurs.

Reverting back to ROM build 920376 allows for the running of PRG files.

This issue only became apparent when trying to use the CBM prg Studio by Arthur Jordison when the created PRG files. Since reverting back to an older ROM build everything seems to be working correctly.

**Comment by lgblgblgb** [comment]
Thanks for the report! The problem is most likely because that's an experimental/development series of ROM (99xxxx), which totally changed how keyboard scanning works and Xemu has to "cheat" to "fake" keypresses to load PRGs which is not detected then by new ROMs because of the totally reworked keyboard scanner routine in the ROM. Meanwhile, to avoid auto-boot DISK images to cause problems, Xemu temporary deactivates the disk image access till the keyboard buffer is "consumed" by the ROM. Since it's never happened because of the changed kbd scanner routine in newer ROMs, it's even left in that state, thus the read error.

So though it's a very annoying thing, I am aware of this and it'sthe nature of the experimental ROM: not supported in emulation, with _this_ functionality at least. Unfortunately it's quite impossible to support both methods with current code flow, and would cause major problems.

**Comment by lgblgblgb** [comment]
Though, I still "reverse the rights ;)" to figure out a better way to support all possible ROMs somehow ...

**Comment by MightyAxle** [comment]
We all appreciate your hard work creating the best possible experience for the MEGA65 through Xemu. It sure has made me feel good about programming in BASIC again! 😊👍

**Comment by lgblgblgb** [comment]
https://discord.com/channels/719326990221574164/781481205639020554/1091513603061977130

It seems even "non-developer" new ROM version(s?) can have problem here.

**Comment by lgblgblgb** [comment]
I found the issue, I think. It's not the keyboard handling changes as I thought before. The issue, that Xemu wants to be ROM version independent (also it works ... worked ... with C64(GO64)/C65/MEGA65 KERNAL as well) thus not using address trapping or anything. It looks for the `READY.` on the actual screen memory, and checks for byte $A0 on the next line (cursor in 'on' state). Here is the problem: it seems, newer ROMs handles cursor differently. Instead of using $A0 (which is also compatible with `GO64`  mode C64 KERNAL) now the screen memory remains, and - I assume - the colour RAM is used instead with probably the inverse hardware attribute for cursor 'inversion'.

**Comment by lgblgblgb** [comment]
Tested with MEGA65 closed ROMs versions 920377, 920383, 990004 also in C64 mode, it seems the fix works in all the cases.

**Comment by MightyAxle** [comment]
Thanks for your sterling work. ROM version 920377 works 100%. 👍ROMs 920383 and 990004 still won't run .PRG files and when you try and load a D81 disk image a read error is returned. I downloaded the newest stable version of Xemu 20230201214849 to test this.

**Comment by lgblgblgb** [comment]
@MightyAxle You need version  20230402002720 available on the "next" branch. On https://github.lgb.hu/xemu/ this is the second "section" of downloadables (aka "future next stable"). The master (aka "stable") branch is something I only regularly update from the then-current next, when next seems to be stable enough in terms of the accumulated changes here since the next "down-merge".

**Comment by MightyAxle** [comment]
We 100% success rate! All ROMs work on 20230402002720 next branch! 👍Thank you! 🏆
