### ISSUE TITLE
MEGA65: White screen instead of config

### ISSUE THREAD

**Issue by nobruinfo** [lgblgblgb/xemu#368]
### Describe the bug

In a running Xmega65 session a special reset leads into the config menu. There you would normally see options for how the machine works. So this is accessible also on a real Mega65.

As this worked up to at least the version of December 2, 2021 later version only show a white screen when entering. This was observed at least in MacOS and Windows versions by the ticket issuer.

### Used version of the project

* Emulator: Xemu65
* Version: February 9, 2023
* ROM: 920377
* CLI arguments: none
* Context menu options: Debug system console
* .img used: newly generated by "SD-Card", "Update files on SD-Card"

### To Reproduce

1. Open Xmega65 and let it boot normally.
2. As a rom is present this ends in the boot message and the READY prompt.
3. Right click into the main window and choose "Reset" - "Reset into utility menu".
4. A text boot message appears, choose key `1` for config.
5. A white screen is given.

### Expected behavior

Instead of the white screen an option programme as shown under "screenshots" should appear.

### Screenshots

![grafik](https://user-images.githubusercontent.com/67829169/218266300-8e3ccbfe-7842-46e1-a53a-b9d093d25731.png)

### Computer/Device (please complete the following information)

- MacOS 10.15 Catalina, Xmega65 of June 2022
- Windows 10 64 bit 21H2, Xmega65 of February 9, 2023

### Additional context

This ticket is not urgent and only meant as a tracking aid for this minor issue.

LGB pointed [in a comment](https://github.com/lgblgblgb/xemu/issues/367#issuecomment-1426847005) that the reason for this bug unfortunately might not be too obvious.

**Comment by lgblgblgb** [comment]
As we've discussed (I write this now, just to be clear) this is nothing to do with the "mount bug". Also, it's a more generic issue that no utility menu programs can be launched, the very same "white screen" problem can be noticed. I'm aware of this problem since a while, but it was low-priority, as truly these utility programs are not as useful as on a real MEGA65 where they can be essential. My only concern more, that the reason `configure` (and other utils) does not run may reveal some deeper emulation problem which can be very useful to be fixed, and may resolve other problems at totally different scenarios as well. Alone just the `configure` utility inaccessibility is more like a "cosmetic" problem.

If you don't mind, I would close this issue and open a new one, since it's a more generic and probably deeper problem than just the accessibility of the `configure` utility.

**Comment by lgblgblgb** [comment]
**MOVED TO #369**
