### ISSUE TITLE
MEGA65/BASIC 10 - Modifying last character of a string using MID$ causes illegal quantity error

### ISSUE THREAD

**Issue by PGNm65** [lgblgblgb/xemu#386]
**Describe the bug**
Modifying the last character of a text string using MID$ to change to another character causes an illegal quantity error.
Actual M65 machine does not cause an error, only XEMU does...

**Used version of the project**
MEGA65 20230201214849
ROM V920377

**To Reproduce**
Steps to reproduce the behavior. As steps as required, do not try to squeeze
everything into one step.
1. ...10 A$="0123456789"
2. ...20 IF MID$(A$,10,1)="9" THEN MID$(A$,10,1)="0"

**Expected behavior**
In above example should simply change the 10th character (last character) of the text string to a 0.

**Screenshots**
N/A

**Computer/Device (please complete the following information):**
 - PC
 - Windows 10 64 bit
 - Firefox

**Additional context**
This will work fine on any modern basic with MID$ and on the actual M65 machine.

**Comment by lgblgblgb** [comment]
Thanks for the report. Are you sure you use the _very same_ ROM with both of MEGA65 and Xemu? Xemu just runs the ROM, the ROM does everything (ie, interpreting BASIC statements, execution etc) as with MEGA65. Surely, Xemu still can have a bug like bad CPU emulation or anything which causes the executed ROM code to misbehave however that's unlikely since it would be effect (probably) many other things as well. But as I've said, it's it for sure not impossible to be triggered by some obscure hardware level emulation bug in Xemu.

**Comment by dansanderson** [comment]
I get consistent incorrect behavior with ROM 920385 in both Xemu and MEGA65. I have filed this here: https://github.com/MEGA65/mega65-rom-public/issues/68

You can resolve this issue, it's not specific to Xemu.

**Comment by lgblgblgb** [comment]
Being a ROM bug, so I close this now. @dansanderson Thanks for the check!!
