### ISSUE TITLE
C65: Emulator not recognizing ROM versions without a "V" prefix.

### ISSUE THREAD

**Issue by calmsacibis995** [lgblgblgb/xemu#413]
**Describe the bug**
This bug is about xemu failing to recognize C65 ROM version without a `V` prefix.

**Used version of the project**
Latest build from git.

Console log:

```
**** The Unusable Commodore 65 emulator from LGB ****
This software is part of the Xemu project: https://github.com/lgblgblgb/xemu
CREATED: zerocool32@zerocool32-mint on Linux 6.8.0-44-generic at Wed Sep 18 07:37:02 PM EEST 2024
CREATED: gcc-compatible 13.2.0 64LE for linux
VERSION: https://github.com/lgblgblgb/xemu.git master 7a9e860ff5ce61dad53de5b9ca18b7100dd2bb8a 20240807161529 custom-build
EMULATE: Commodore 65 (c65): xc65 (../../build/bin/xc65.native) for c65 on linux (native) using cc
LICENSE: Copyright (C)2016-2024 Gábor Lénárt (aka LGB) lgb@lgb.hu http://lgb.hu/
LICENSE: This software is a GNU/GPL version 2 (or later) software.
LICENSE: <http://gnu.org/licenses/gpl.html>
LICENSE: This is free software; you are free to change and redistribute it.
LICENSE: There is NO WARRANTY, to the extent permitted by law.

FILE: file @c65-default.cfg opened as /home/zerocool32/.local/share/xemu-lgb/c65/c65-default.cfg with base mode-set as fd=5
FILE: 338 bytes loaded from file: /home/zerocool32/.local/share/xemu-lgb/c65/c65-default.cfg
CFG: Default config file @c65-default.cfg has been used
CFG: CLI parsing is done without error.
FILE: file @c65-template.cfg.TMP opened as /home/zerocool32/.local/share/xemu-lgb/c65/c65-template.cfg.TMP with base mode-set as fd=5
FILE: 3135 bytes saved into file: @c65-template.cfg.TMP
FILE: renaming file: /home/zerocool32/.local/share/xemu-lgb/c65/c65-template.cfg.TMP -> /home/zerocool32/.local/share/xemu-lgb/c65/c65-template.cfg
Logging into file: not enabled.
SDL: no SDL subsystem initialization has been done yet, do it!
SDL version: (SDL-release-2.30.0-0-g859844eae (Ubuntu 2.30.0+dfsg-1build3)) compiled with 2.30.0, used with 2.30.0 on platform Linux
SDL system info: 64 bits LE, 16 cores, l1_line=64, RAM=15867Mbytes, max_alignment=16, CPU features: 3DNow=0 AVX=1 AVX2=1 AltiVec=0 MMX=1 RDTSC=1 SSE=1 SSE2=1 SSE3=1 SSE41=1 SSE42=1
SDL drivers: video = x11 (1920x1080), audio = pulseaudio
TIMING: sleep = nanosleep, query = SDL_GetPerformanceCounter
SDL preferences directory: /home/zerocool32/.local/share/xemu-lgb/c65/
SDL: opening window at (536805376,536805376) with size of (704,464)
SDL window native pixel format: SDL_PIXELFORMAT_RGB888
SDL renderer driver #0: "opengl"
SDL renderer driver #1: "opengles2"
SDL renderer driver #2: "software"
SDL renderer used: "opengl" max_tex=32768x32768 tex_formats=8 (ARGB8888 ABGR8888 RGB888 BGR888 YV12 IYUV NV12 NV21)
SDL: creating main texture 704 x 232

FILE: file @keymap-default.cfg opened as /home/zerocool32/.local/share/xemu-lgb/c65/keymap-default.cfg with base mode-set as fd=29
HID: 93 key bindings has been added as the default built-in configuration
FILE: @keymap.cfg cannot be open, tried path(s):  /home/zerocool32/.local/share/xemu-lgb/c65/keymap.cfg
HID: cannot open keymap user config file (maybe does not exist), ignoring: @keymap.cfg
HOSTFS: error (host_status=0) is set to "73, XEMU SOFTWARE CBM-DOS SUBSET,00,00": init.
HOSTFS: init @ /home/zerocool32/.local/share/xemu-lgb/c65//hostfs/
DMA: initializing DMA engine for chip revision 1 (initially, may be modified later!), dyn_mode=NEVER(C65), modulo_support=DISABLED.
FILE: file #c65-system.rom opened as /home/zerocool32/.local/share/xemu-lgb/c65/default-files/c65-system.rom with base mode-set as fd=29
FILE: 131072 bytes loaded from file: /home/zerocool32/.local/share/xemu-lgb/c65/default-files/c65-system.rom
ROM: version check failed (no leading 'V')
ROM: version check suggests DMA revision 1
WARNING: ROM version cannot be detected, and DMA revision auto-detection was requested.
Defaulting to revision 1.
Warning, this may cause incorrect behaviour!
DMA: setting chip revision to #1 based on the ROM auto-detection
D81: initial subsystem reset
C65FDC: configuring F011 FDC (#0) with have_disk=0, can_write=1
C65FDC: configuring F011 FDC (#1) with have_disk=0, can_write=1
D81: attach file request with empty file name, not using FS based disk attachment.
D81: attach file request with empty file name, not using FS based disk attachment.
CPU[65CE02]: RESET, PC=EE0B, BCD_behaviour=65C02+
GUI: no GUI was specified, using the first available one from this list: gtk osd plugin none
GUI: using "gtk" (GTK3 based Xemu UI implementation)
GTK: setting environment variable GDK_BACKEND=x11 to avoid possible GTK backend mismatch with SDL
GUI: GTK3 initialized, 2 iterations.
```

**To Reproduce**
Steps to reproduce the behavior. As steps as required, do not try to squeeze
everything into one step.
1. Acquire a C65 ROM with a version prefix that does not begin with `V` (I used `AER.6EP1`).
2. Copied to the ROM directory.
3. Started the emulator.
4. It should display the warning message that appears in the screenshot below.

**Expected behavior**
Recognized the ROM as a C65 ROM, without any warning messages appearing either on the emulator window, nor on the console.

**Screenshots**
![2024-09-18_21-24](https://github.com/user-attachments/assets/1817c091-e89c-4d11-a3ec-a54ac709a8fc)

**Computer/Device (please complete the following information):**
 - Device/Platform: PC
 - OS and its version: Linux Mint 22 64-bit

**Additional context**
None.

**Comment by lgblgblgb** [comment]
@calmsacibis995 Thanks for the report! That warning is intentional. The problem: C65 was never finished, (ok, maybe not every, but ...) every C65s are a bit different. Sometimes not even just a bit. For example there is a huge incompatibility with DMA chip which can be either revision A or rev B. They're incompatible. Older ROMs needs F018A (rev A), newer ones requires F018B (rev B). Xemu uses that 'V' string (and the date after it) to try to figure out which DMA chip should be emulated for the given ROM to be able to work at all. However, without that, Xemu cannot be sure it knows which DMA revision should be emulated. Surely, I can use the idea, that without the 'V' string it must be rev A, and I guess it should work with older ROMs (very old ROMs does not have that V stuff in my experience), but that's the reason it's only a warning window and not a fatal error.

Though, I also understand that it can be annoying to always get that warning. I am not really sure what should be the best strategy here to please all users, not having a warning can be also problematic, when user cannot understand why their ROM of choice do not work then with Xemu without any feedback/error/warning though. Probably I should add a CLI option to mute this warning (all CLI options can be placed in config file).

**Comment by calmsacibis995** [comment]
@lgblgblgb I understand the intentional use of the warning. We could enhance the detection routine so that it will detect the presence of a ROM without a 'V' prefix (in my testing, I found that the 'V' prefix was added around late 1990-early 1991)

**Comment by lgblgblgb** [comment]
Yes, I would classify ROMs into three categories:

1. "very old" ROMs, not even have "V" string -> _probably_ requires F018A DMA (logically, since F018B was introduced later at all)
2. "old" ROMs, "V910522" and before -> requires F018A DMA
3. "new" ROMs, after "V910522" -> requires F018B DMA

Though I would still want a warning in case of "1." since it can be other problem as well (ie, the binary itself is not even a valid C65  ROM). But probably I should decrease the verbosity of the problem, and adding only a warning on the Xemu output, not as a form of a warning window, which can be annoying after a while ...

**Comment by lgblgblgb** [comment]
Fixed in `dev` branch. It can take a long time to get into the `master` branch, as the usual way is go into `next` first, then from time to time a "mass-merge" into `master`. Now I am before that, only in `dev`. Though you can try to build now from `dev` branch.

**Comment by lgblgblgb** [comment]
Closing this now. If you have further problem with this specific issue, feel free to comment. Thanks!
