### ISSUE TITLE
MacOS Platform: develop native, MacOS based GUI components in pair with GTK/Windows ones

### ISSUE THREAD

**Issue by lgblgblgb** [lgblgblgb/xemu#86]
Xemu has some GUI, GTK3, and Windows native. For MacOS, it would be superb, to have native MacOS GUI. It also helps to keep dependencies at minimum (other than SDL2 itself), since GTK3 is kinda a big stuff with many components, just for some popup menu and file selector box. Xemu has already UI components for that on Windows (using native windows API). It should be done for MacOS as well. Note, it must be plain C, nothing too crazy ...

**Comment by hernandp** [comment]
I managed to link GTK3 as shown, although seems to have issues (seems unresponsive).

![image](https://user-images.githubusercontent.com/4740613/73046404-c57f9500-3e50-11ea-8efd-280f3be1d74b.png)

Regarding a native implementation,  plain C implementation is hellish because to use Cocoa you must do low-level calls to the ObjC Runtime.  The correct way I think should be to build an objC source with Cocoa calls, compile it with gcc and link the object code  against a "wrapper" C source included from `emutools_gui.c`.  
If urgent tasks are priority,  GTK+3 could be a transitional solution for this.

**Comment by hernandp** [comment]
#106 PR addressed this.

**Comment by lgblgblgb** [comment]
PR #108 to merge it to the official dev tree. Commit 08f43f9523654afbbfbe713f36b13d36bd2de723

**Comment by lgblgblgb** [comment]
So we have UI for Mac thanks for Hernán. If it has problems, bugs, or anything, that's another question, and a separate issue. Great work, thanks, Hernán!
